const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const context=vm.createContext({console});vm.runInContext(fs.readFileSync('src/data.js','utf8')+'\n'+fs.readFileSync('src/sim.js','utf8')+'\nglobalThis.api={DATA,Sim};',context);const {DATA,Sim}=context.api;let count=0;function test(name,fn){try{fn();console.log('PASS '+name);count++}catch(e){console.error('FAIL '+name);throw e}}function advance(s,secs){for(let i=0;i<secs*10;i++)Sim.tick(s,.1)}function place(s,id){let n=Sim.npc(s,id);n.present=true;n.away=false;s.player.x=n.x;s.player.y=n.y;return n}function at(s,id){let p=DATA.stations.find(x=>x.id===id);s.player.x=p.x;s.player.y=p.y}function prep(opts,leak=false){let s=Sim.fresh();advance(s,50);Sim.learn(s,'wagons','test witness');Sim.learn(s,'warning','Bram');if(leak){place(s,'mira');assert(Sim.act(s,'share','mira'))}at(s,'board');assert(Sim.act(s,'dispatch',null,opts));return s}
test('every station is reachable from entrance, office, booth and bar',()=>{for(let start of [{x:480,y:597},{x:280,y:160},{x:800,y:220},{x:80,y:400}])for(let st of DATA.stations){if(Sim.dist(start,st)<35)continue;let route=Sim.route(start,st);assert(route.length,st.id+' from '+JSON.stringify(start));assert(Sim.dist(route.at(-1),st)<65);for(let p of route)assert(!Sim.blocked(p.x,p.y))}});
test('complete keyboard routes do not pass through tables or partitions',()=>{let s=Sim.fresh();for(let dir of ['left','up','right','down']){for(let i=0;i<600;i++){Sim.tick(s,.1,{[dir]:true});assert(!Sim.blocked(s.player.x,s.player.y))}}});
test('quiet information is not learned at a distance',()=>{let s=Sim.fresh();s.player.x=90;s.player.y=110;advance(s,140);assert.equal(Object.keys(s.knowledge).length,0);assert.equal(s.notes.length,0)});
test('proximity and lingering acquire a sourced warning',()=>{let s=Sim.fresh();advance(s,30);s.player.x=350;s.player.y=480;advance(s,15);assert(s.knowledge.warning);assert.equal(s.knowledge.warning.observations[0].source,'Bram')});
test('partitions block perception and accessibility does not reveal through walls',()=>{let s=Sim.fresh(),n=Sim.npc(s,'mira');n.x=775;n.y=150;let t=DATA.talks.find(t=>t.id==='booth');s.player.x=680;s.player.y=150;assert.equal(Sim.perceive(s,t).tier,0);s.settings.clear=true;assert.equal(Sim.perceive(s,t).tier,0)});
test('duplicate sources never self-corroborate',()=>{let s=Sim.fresh();Sim.learn(s,'wagons','Oren');Sim.learn(s,'wagons','Oren');assert.equal(s.knowledge.wagons.observations.length,1);assert.notEqual(s.knowledge.wagons.status,'Corroborated');Sim.learn(s,'wagons','Tomas');assert.equal(s.knowledge.wagons.status,'Corroborated')});
test('all world actions and time freeze while paused',()=>{let s=Sim.fresh();advance(s,50);place(s,'nell');s.player.carry='tea';s.paused=true;let before=JSON.stringify(s);for(let verb of ['serve','hire','talk','report','withhold','take','dispatch','sleep','discard'])assert.equal(Sim.act(s,verb,'nell'),false);advance(s,20);assert.equal(JSON.stringify(s),before)});
test('hospitality earns money and a specific remembered kindness',()=>{let s=Sim.fresh();at(s,'tea');assert(Sim.act(s,'take','tea'));let n=place(s,'nell');assert(Sim.act(s,'serve','nell'));assert.equal(s.coins,29);assert.equal(n.familiar,2);assert(n.memory[0].includes('tea'))});
test('hiring staff serves physical public tables and preserves upstairs blind spot',()=>{let s=Sim.fresh();advance(s,10);place(s,'nell');assert(Sim.act(s,'hire','nell'));advance(s,100);assert(s.npcs.some(n=>n.id!=='nell'&&n.served));assert.equal(Sim.npc(s,'ivo').served,0)});
test('prepared expedition physically exits and remains absent for days',()=>{let s=prep({bram:true,supplies:true,warning:true,cautious:true});advance(s,12);assert(!Sim.npc(s,'cedric').present);assert(!s.quest.resolved);Sim.nextDay(s);advance(s,60);assert(!Sim.npc(s,'cedric').present);assert(!s.quest.resolved);Sim.nextDay(s);advance(s,30);assert(s.quest.resolved);assert(Sim.npc(s,'cedric').present);place(s,'cedric');assert(Sim.act(s,'debrief','cedric'));assert.equal(s.quest.outcome,'proof');assert(s.knowledge.ledger)});
test('Mira disclosure changes outcome and who knows the rumor',()=>{let s=prep({bram:true,supplies:true,warning:true,cautious:true},true);Sim.nextDay(s);Sim.nextDay(s);advance(s,30);place(s,'cedric');Sim.act(s,'debrief','cedric');assert.equal(s.quest.outcome,'compromised');assert(!s.knowledge.ledger);assert(s.knowledge.wagons.knownBy.includes('Reed Knives'));assert(s.relationships['cedric:mira'].includes('distrusts'))});
test('underprepared expedition returns injured, without arbitrary mortality',()=>{let s=prep({bram:false,supplies:false,warning:false,cautious:false});Sim.nextDay(s);Sim.nextDay(s);advance(s,30);assert.equal(s.quest.outcome,'injured');assert(Sim.npc(s,'cedric').present)});
test('critical fallback letter remains locally inspectable',()=>{let s=Sim.fresh();Sim.nextDay(s);Sim.nextDay(s);advance(s,30);assert(!s.knowledge.wagons);at(s,'board');assert(Sim.act(s,'inspect','letter'));assert(s.knowledge.wagons);assert(s.knowledge.diversion)});
test('seven unobserved days complete safely with debt and an ending',()=>{let s=Sim.fresh();advance(s,1262);assert(s.ended);assert.equal(s.day,7);assert(s.paused);assert(Sim.summary(s).length>5)});
test('save roundtrip preserves expedition, evidence and memories',()=>{let s=prep({bram:true,supplies:true,warning:true,cautious:true},true);let restored=JSON.parse(JSON.stringify(s));assert.equal(JSON.stringify(restored),JSON.stringify(s));advance(restored,10);assert(restored.world.leak);assert(restored.quest.party.includes('bram'))});
console.log('\n'+count+' scenario regressions passed.');

