/* Stable-ID character, story and layout content. */
const DATA = {
  npcs: [
    {
      id: "cedric",
      name: "Cedric",
      role: "Aspiring swordsman",
      color: "#be764b",
      hair: "#d7b76c",
      favorite: "ale",
      x: 380,
      y: 350,
      arrival: 8,
      depart: 155,
      ambition:
        "My sister is apprenticing to a glassmaker. Someone has to pay the fee.",
      intro:
        "I have a sword. Bram says that is different from being a swordsman.",
      faction: "Road company",
    },
    {
      id: "mira",
      name: "Mira",
      role: "Scout • claims to know every road",
      color: "#7a8c79",
      hair: "#27262b",
      favorite: "wine",
      x: 775,
      y: 240,
      arrival: 18,
      depart: 162,
      ambition:
        "I am saving enough money to stop taking jobs for people I do not trust.",
      intro:
        "I scout the roads around Rookcross. If you hear about trouble out there, tell me. I may know someone who can help.",
      faction: "Reed Knives",
    },
    {
      id: "nell",
      name: "Nell",
      role: "Server looking for a steady wage",
      color: "#759fa6",
      hair: "#b96543",
      favorite: "tea",
      x: 265,
      y: 265,
      arrival: 0,
      depart: 172,
      ambition: "I want to buy a small boat. A steady wage here would help.",
      intro:
        "I used to serve tables here for your aunt. If you need help, I would like the job.",
      faction: "Rookcross locals",
    },
    {
      id: "oren",
      name: "Oren",
      role: "Merchant • wagon owner",
      color: "#ad8b4e",
      hair: "#e2d1b1",
      favorite: "wine",
      x: 680,
      y: 455,
      arrival: 28,
      depart: 145,
      ambition:
        "My drivers need wages, and the horses need feed. I cannot keep losing shipments.",
      intro:
        "Three of my wagons are missing on the Blackwood road. I suspect bandits, but the watch has found no proof.",
      faction: "Merchant compact",
    },
    {
      id: "tomas",
      name: "Tomas",
      role: "Watch constable",
      color: "#658aa7",
      hair: "#635443",
      favorite: "stew",
      x: 590,
      y: 350,
      arrival: 34,
      depart: 168,
      ambition:
        "I need evidence I can put in a report. Rumors alone will not get those wagons back.",
      intro:
        "I am investigating the missing wagons. If someone tells you what happened, ask whether they saw it themselves.",
      faction: "Crown watch",
    },
    {
      id: "aldous",
      name: "Aldous",
      role: "Hearth cleric",
      color: "#aa9e79",
      hair: "#aaa795",
      favorite: "tea",
      x: 430,
      y: 510,
      arrival: 45,
      depart: 159,
      ambition:
        "We need blankets and food at the chapel. The loss of trade has left several families without work.",
      intro:
        "I look after the chapel. We are sheltering families who have lost work since the wagons stopped coming.",
      faction: "Hearth church",
    },
    {
      id: "bram",
      name: "Bram",
      role: "Veteran dwarf • reluctant mentor",
      color: "#8b6e64",
      hair: "#b8b1a1",
      favorite: "ale",
      x: 350,
      y: 510,
      arrival: 12,
      depart: 160,
      ambition:
        "I want Cedric to survive his first jobs. He is brave, but he is still learning.",
      intro:
        "Cedric wants to take work on the road. I am trying to teach him how to get home in one piece.",
      faction: "Road company",
    },
    {
      id: "ivo",
      name: "Ivo",
      role: "Wizard • room two",
      color: "#8d7ea7",
      hair: "#ddd4bd",
      favorite: "stew",
      x: 890,
      y: 110,
      arrival: 55,
      depart: 174,
      ambition:
        "I found this inn mentioned in three old treaties. I want to know why people kept meeting here.",
      intro:
        "I am staying in room two with my magical pet. Please tell me you are not charging it for a separate bed.",
      faction: "Mages register",
    },
  ],
  rumors: {
    wagons: {
      title: "The missing Westbridge wagons",
      text: "Three wagons are missing on the Blackwood road. Their fate is uncertain.",
      kind: "Unverified claim",
    },
    diversion: {
      title: "A voluntary detour?",
      text: "The wagons may have turned toward the old tollhouse willingly.",
      kind: "Lead",
    },
    ledger: {
      title: "Payments at the tollhouse",
      text: "A stamped ledger records Oren paying to divert trade past Rookcross.",
      kind: "Confirmed evidence",
    },
    warning: {
      title: "The broken north bridge",
      text: "The north bridge is rotten. A survey should take the ridge with rope.",
      kind: "Practical warning",
    },
    carving: {
      title: "Names beneath the hearth",
      text: "The inn carving matches a treaty seal. Old keepers recorded meetings here.",
      kind: "Unresolved connection",
    },
    knives: {
      title: "Mira and the Reed Knives",
      text: "Mira passes useful road news to the Reed Knives. Her independence is a claim.",
      kind: "Sensitive testimony",
    },
  },
  talks: [
    {
      id: "wagons",
      days: [1, 2],
      start: 42,
      end: 92,
      a: "oren",
      b: "tomas",
      fragment: "…three wagons…",
      line: "Oren: Three Westbridge wagons. Gone. Bandits, obviously. Tomas: Funny. No broken wheels, no bodies.",
      rumor: "wagons",
    },
    {
      id: "mentor",
      days: [1, 2, 3],
      start: 22,
      end: 65,
      a: "bram",
      b: "cedric",
      fragment: "…not the north bridge…",
      line: "Bram: The north bridge is rotten. Take rope and use the ridge. Cedric: I thought you would say bring a bigger sword.",
      rumor: "warning",
    },
    {
      id: "booth",
      days: [1, 2, 3],
      start: 99,
      end: 137,
      a: "mira",
      b: "oren",
      whisper: true,
      fragment: "…paid to turn…",
      line: "Mira: You paid the drivers to bring the wagons to the tollhouse. Oren: Keep your voice down. I paid you not to tell anyone.",
      rumor: "diversion",
    },
    {
      id: "confidence",
      days: [2, 3, 5],
      start: 66,
      end: 96,
      a: "mira",
      b: "nell",
      whisper: true,
      fragment: "…the Knives expect…",
      line: "Mira: The Reed Knives want me to tell them about valuable shipments. Nell: Does Cedric know you work for them?",
      rumor: "knives",
    },
    {
      id: "quiet",
      days: [4],
      start: 36,
      end: 98,
      a: "cedric",
      b: "nell",
      fragment: "…blue glass…",
      line: "Cedric: My sister made you this blue glass bead. Sorry it is a bit uneven. Nell: She made it herself? Tell her I love it.",
    },
    {
      id: "soup",
      days: [1, 3, 4, 6],
      start: 111,
      end: 152,
      a: "aldous",
      b: "bram",
      fragment: "…a quiet evening…",
      line: "Aldous: It is good to have a quiet evening for once. Bram: And hot soup. Do not forget the soup.",
    },
    {
      id: "seal",
      days: [3, 5, 6],
      start: 64,
      end: 115,
      a: "ivo",
      b: "aldous",
      fragment: "…same carved mark…",
      line: "Ivo: This hearth carving also appears on the Treaty of Ash. Aldous: Your aunt kept a list of people who met here. Her old ledger might help.",
      rumor: "carving",
    },
    {
      id: "beard",
      days: [4, 7],
      start: 110,
      end: 152,
      a: "bram",
      b: "tomas",
      fragment: "…under the beard…",
      line: "Tomas: I need to check whether you are carrying a weapon. Bram: There is an axe hanging from my belt, Tomas. You can stop looking in my beard.",
    },
  ],
  walls: [
    {
      x: 710,
      y: 35,
      w: 18,
      h: 155,
    },
    {
      x: 710,
      y: 300,
      w: 18,
      h: 38,
    },
    {
      x: 710,
      y: 338,
      w: 235,
      h: 18,
    },
    {
      x: 710,
      y: 35,
      w: 235,
      h: 14,
    },
    {
      x: 728,
      y: 179,
      w: 65,
      h: 12,
    },
    {
      x: 870,
      y: 179,
      w: 75,
      h: 12,
    },
    {
      x: 35,
      y: 185,
      w: 175,
      h: 18,
    },
    {
      x: 295,
      y: 185,
      w: 100,
      h: 18,
    },
  ],
  furniture: [
    {
      x: 95,
      y: 230,
      w: 75,
      h: 160,
      type: "bar",
    },
    {
      x: 330,
      y: 375,
      w: 100,
      h: 50,
      type: "table",
    },
    {
      x: 530,
      y: 375,
      w: 100,
      h: 50,
      type: "table",
    },
    {
      x: 335,
      y: 540,
      w: 125,
      h: 40,
      type: "table",
    },
    {
      x: 640,
      y: 490,
      w: 105,
      h: 45,
      type: "table",
    },
    {
      x: 790,
      y: 260,
      w: 95,
      h: 40,
      type: "table",
    },
    {
      x: 805,
      y: 65,
      w: 115,
      h: 55,
      type: "bed",
    },
    {
      x: 240,
      y: 65,
      w: 120,
      h: 65,
      type: "desk",
    },
  ],
  stations: [
    {
      id: "ale",
      name: "Ale cask",
      x: 77,
      y: 255,
    },
    {
      id: "wine",
      name: "Wine cask",
      x: 77,
      y: 305,
    },
    {
      id: "tea",
      name: "Tea kettle",
      x: 77,
      y: 355,
    },
    {
      id: "stew",
      name: "Stew pot",
      x: 120,
      y: 440,
    },
    {
      id: "board",
      name: "Letters & expedition board",
      x: 280,
      y: 153,
    },
    {
      id: "hearth",
      name: "Carved hearth",
      x: 510,
      y: 82,
    },
    {
      id: "room",
      name: "Guest room",
      x: 875,
      y: 160,
    },
    {
      id: "bed",
      name: "Close the inn",
      x: 105,
      y: 110,
    },
  ],
  daily: {
    cedric: [
      "Bram checked my boots before my sword. Apparently blisters end more journeys than bandits do.",
      "My sister is learning to make glass. She sent me a bead she made herself.",
      "If I take a job on the road, will you keep my usual chair free? I know that sounds silly.",
      "I gave Nell the blue bead my sister made. She hung it by a window. I think she liked it.",
      "Bram says I need to practice checking my supplies. I would rather practice with my sword, but he has a point.",
      "People leave the boring parts out of adventure stories. Nobody mentions wet socks.",
      "My sister wants a letter. I am trying to think of something that will impress her without making her worry.",
    ],
    mira: [
      "I like the booth. It is easier to talk there without the whole room listening.",
      "Cedric thinks I never get frightened. I check every bridge before I cross it. That is how frightened I get.",
      "A few people helped me when I was short of money. Now they keep asking for favors.",
      "It is quiet tonight. I might finish a drink without somebody offering me a job.",
      "Some of my clients are unpleasant. Unfortunately, they tend to pay on time.",
      "Cedric keeps asking about the people I work for. I have been avoiding the conversation.",
      "I would like to take a straightforward job next week. Find a lost dog, perhaps. Something that does not involve lying.",
    ],
    nell: [
      "The table nearest the fire wobbles. Your aunt folded an old letter under the short leg. I have left it there.",
      "Cedric looks toward the door every time someone arrives. I think he is hoping to be offered work.",
      "Oren counted his change twice. If he hires anyone to find those wagons, get the fee in advance.",
      "Cedric gave me a glass bead his sister made. It is a little uneven, but the blue is lovely.",
      "I checked the price of a boat. I will be saving for a while yet.",
      "If someone comes back hurt, send for Aldous. I can bring them food while we wait.",
      "It is good to see people using the inn again. Your aunt would have liked that.",
    ],
    oren: [
      "You will need regular deliveries of food and ale. I can arrange them, provided you pay on time.",
      "Rookcross used to have six carriers. Half have moved away because there is not enough work.",
      "A cup of wine in the booth, if you can. I need a quiet place to go through these accounts.",
      "I have spent the afternoon checking unpaid invoices. I would much rather be drinking.",
      "I know people complain about my prices. I still have drivers and horses to pay for.",
      "I have brought food into Rookcross through some very bad winters. People seem to forget that.",
      "We will still need supplies next week, whatever happens with the wagons.",
    ],
    tomas: [
      "I had to remove a goat from the market again. Same goat. Same vegetable stall.",
      "The wagon tracks turn toward the old tollhouse. I found no sign of a fight at the junction.",
      "My captain wants an arrest. I would prefer to find out what happened first.",
      "Bram refuses to take his hat off for searches. Apparently that is an old argument with the watch.",
      "My deputy has patched the same boot three times. We have been waiting two months for new equipment.",
      "I am checking reports about the old tollhouse. Tell me what you saw, and what you only heard from someone else.",
      "If you give me a name, tell me where you heard it. I need to be able to check the story.",
    ],
    aldous: [
      "People who arrive at the chapel hungry get a meal before a sermon. It seems only fair.",
      "We have three families sleeping in the chapel. I am looking for spare blankets.",
      "Ivo asked about the carving on your hearth. Your aunt used to keep notes about the people who met here.",
      "Nobody needs my help just now. I intend to sit by the fire and enjoy that.",
      "We made room for another family at the chapel. It is crowded, but they are out of the rain.",
      "If an adventurer comes back injured, send someone for me. I keep dressings ready.",
      "A hot meal will not repair the trade road, but it will help the people waiting for work.",
    ],
    bram: [
      "A rope and dry socks. Those are the things a new adventurer always forgets.",
      "The north bridge is rotten. Anyone heading that way should take rope and use the ridge path.",
      "Cedric asked how to look fearless. I told him to check behind him before posing with his sword.",
      "Hot soup, a sturdy chair, and no wolves. This is a perfectly good evening.",
      "I still notice when a regular is away. I like knowing people have made it home.",
      "I wish someone had taught me to turn back when I was Cedric's age. It would have saved me a few scars.",
      "Cedric is starting to listen when I talk about supplies. I am taking that as progress.",
    ],
    ivo: [
      "My magical pet sleeps in my coat pocket. It does not need its own bed.",
      "My pet knocked over a cup of wine. That is why its paws are purple. I will pay for the cleaning.",
      "I found a drawing of the hearth carving on a copy of the Treaty of Ash. I wonder who put it there first.",
      "I am taking a day off from experiments. My pet has been hiding whenever I open the reagent case.",
      "Your aunt's old ledger lists names and meeting dates. It does not look like a book of unpaid bills.",
      "Some of the stones under the hearth look older than the inn. I would like to examine them when the fire is out.",
      "I will bring my copies of the treaties next week. Perhaps we can work out who met here.",
    ],
  },
  dayNames: [
    "First light",
    "Familiar faces",
    "A letter in the rain",
    "Nothing much, thankfully",
    "The empty chair",
    "What comes home",
    "The keeper of things",
  ],
};
if (typeof module !== "undefined") module.exports = DATA;
