const Sim = (()=>{
 const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
 const obstacles=[...DATA.walls,...DATA.furniture];
 function blocked(x,y,r=11){return x<47+r||x>941-r||y<47+r||y>615-r||obstacles.some(o=>x>o.x-r&&x<o.x+o.w+r&&y>o.y-r&&y<o.y+o.h+r)}
 function line(a,b){let d=dist(a,b);for(let i=0;i<=d;i+=6){let t=i/(d||1),x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t;if(DATA.walls.some(o=>x>o.x&&x<o.x+o.w&&y>o.y&&y<o.y+o.h))return false}return true}
 function route(a,b){const step=20,key=(x,y)=>x+','+y;
  const nearest=p=>{let points=[];for(let dx=-2;dx<=2;dx++)for(let dy=-2;dy<=2;dy++){let x=Math.round(p.x/step)+dx,y=Math.round(p.y/step)+dy;if(!blocked(x*step,y*step))points.push({x,y})}return points.sort((u,v)=>Math.hypot(u.x*step-p.x,u.y*step-p.y)-Math.hypot(v.x*step-p.x,v.y*step-p.y))[0]};
  let goal=nearest(b),start=nearest(a);if(!goal||!start)return [];let q=[start],seen=new Map([[key(start.x,start.y),null]]),last=null;
  for(let h=0;h<q.length;h++){let n=q[h];if(n.x===goal.x&&n.y===goal.y){last=n;break}for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){let x=n.x+dx,y=n.y+dy,k=key(x,y);if(!seen.has(k)&&!blocked(x*step,y*step)){seen.set(k,n);q.push({x,y})}}}
  if(!last)return [];let out=[];while(last){out.unshift({x:last.x*step,y:last.y*step});last=seen.get(key(last.x,last.y))}return out;
 }
 function fresh(){return {version:1,day:1,time:0,coins:24,debt:0,player:{x:250,y:320,name:'Keeper',color:'#d6ab5f',carry:null,path:[]},npcs:DATA.npcs.map((n,i)=>({...n,x:480+i*4,y:597,present:false,path:[],memory:[],known:[],familiar:0,served:0,away:false,state:'arriving'})),knowledge:{},heard:{},events:{},relationships:{'cedric:mira':'trusting','cedric:bram':'apprentice and mentor','cedric:nell':'tentative fondness'},world:{trade:'Wagons avoid Rookcross',leak:false,sold:false,exploited:false,guard:'No complaint filed'},staff:{hired:false,reports:[]},quest:null,notes:[],evidence:[],paused:false,ended:false,settings:{clear:false,slow:false},pour:0,toast:'',toastTime:0}}
 function note(s,t){s.notes.unshift({day:s.day,text:t});s.notes=s.notes.slice(0,50)}
 function say(s,t){s.toast=t;s.toastTime=7}
 function learn(s,id,source,channel='heard',confirmed=false){let k=s.knowledge[id];if(!k)k=s.knowledge[id]={id,observations:[],knownBy:['keeper'],status:DATA.rumors[id].kind};if(!k.observations.some(o=>o.source===source)){k.observations.push({source,origin:source.includes('recalling ')?source.split('recalling ')[1]:source,channel,day:s.day});if(new Set(k.observations.map(o=>o.origin||o.source)).size>1)k.status='Corroborated';}if(confirmed)k.status='Confirmed evidence';return k}
 function npc(s,id){return s.npcs.find(n=>n.id===id)}
 function activeTalks(s){return DATA.talks.filter(t=>t.days.includes(s.day)&&s.time>=t.start&&s.time<t.end&&npc(s,t.a).present&&npc(s,t.b).present&&!npc(s,t.a).away&&!npc(s,t.b).away).filter(t=>dist(npc(s,t.a),npc(s,t.b))<145)}
 function perceive(s,t,observer=s.player){let a=npc(s,t.a),d=dist(observer,a),visible=line(observer,a);let familiar=observer===s.player?a.familiar:0;let near=(t.whisper?75:118)+(s.settings.clear?30:0)+Math.min(15,familiar*3);if(!visible)return {tier:0};if(d<near)return {tier:3};if(d<near+70)return {tier:2};if(d<340)return {tier:1};return {tier:0}}
 function move(n,dt,speed=65){if(!n.path?.length)return;let p=n.path[0],d=dist(n,p),v=speed*dt;if(d<=v){n.x=p.x;n.y=p.y;n.path.shift()}else{n.x+=(p.x-n.x)/d*v;n.y+=(p.y-n.y)/d*v}}
 function target(n,p){if(!n.goal||dist(n.goal,p)>12){n.goal={...p};n.path=route(n,p)}}
 function resetDay(s){for(let n of s.npcs){n.present=false;n.served=0;n.path=[];n.goal=null;n.x=480;n.y=597} s.heard={};s.events['room'+s.day]=false}
 function nextDay(s){if(s.paused)return false;if(s.day===7){s.ended=true;s.paused=true;return true}s.coins-=s.staff.hired?7:4;if(s.coins<0){s.debt+=-s.coins;s.coins=0;note(s,'Oren covered the shortfall. He called it a favor, not a loan.')}s.day++;s.time=0;resetDay(s);note(s,'Morning: '+DATA.dayNames[s.day-1]+'.');return true}
 function resolve(s){let q=s.quest;if(!q||q.resolved||s.day<q.returnDay)return;q.resolved=true;const safe=q.bram&&q.supplies&&q.warning&&q.cautious;q.outcome=safe?(s.world.leak?'compromised':'proof'):'injured';for(let id of q.party){let n=npc(s,id);n.away=false;n.present=false;n.goal=null;n.memory.push(q.outcome==='injured'?'You sent us onto a broken road without enough preparation.':'You made sure we had a way home.')}s.relationships['cedric:bram']=q.bram?'Bram brought Cedric home':'Cedric wishes Bram had come';if(q.outcome==='injured')s.relationships['cedric:mira']=s.world.leak?'Cedric feels betrayed':'Mira worries for Cedric';}
 function tick(s,dt,input={}){if(s.paused||s.ended)return;dt=Math.min(dt,.1);s.time+=dt/(s.settings.slow?1.7:1);s.toastTime=Math.max(0,s.toastTime-dt);let dx=(input.right?1:0)-(input.left?1:0),dy=(input.down?1:0)-(input.up?1:0);if(dx||dy){s.player.path=[];let l=Math.hypot(dx,dy),v=155*dt;if(!blocked(s.player.x+dx/l*v,s.player.y))s.player.x+=dx/l*v;if(!blocked(s.player.x,s.player.y+dy/l*v))s.player.y+=dy/l*v}else move(s.player,dt,155);
  resolve(s);
  for(let n of s.npcs){if(n.away){if(n.present){target(n,{x:480,y:599});move(n,dt,78);if(dist(n,{x:480,y:599})<20)n.present=false}continue}if(s.time>=n.arrival&&s.time<n.depart&&!n.present&&!s.events['left'+s.day+n.id]){n.present=true;n.x=n.id==='mira'?915:480;n.y=n.id==='mira'?220:597;n.goal=null}
   if(!n.present)continue;if(s.time>=n.depart){target(n,{x:480,y:599});if(dist(n,{x:480,y:599})<20){n.present=false;s.events['left'+s.day+n.id]=true;continue}}
   else {let base=DATA.npcs.find(v=>v.id===n.id),p={x:base.x,y:base.y};let talk=DATA.talks.find(t=>t.days.includes(s.day)&&s.time>=t.start-8&&s.time<t.end&&(t.a===n.id||t.b===n.id));if(talk){let host=DATA.npcs.find(v=>v.id===talk.a);p={x:Math.min(910,host.x+(talk.b===n.id?65:0)),y:host.y}}
    if(n.id==='mira'&&s.world.leak&&s.day>=3)p={x:775,y:230};
    if(n.id==='nell'&&s.staff.hired){let guest=s.npcs.find(g=>g.present&&!g.away&&!g.served&&g.id!=='nell'&&g.x<710&&s.time>30);if(guest){p={x:guest.x-28,y:guest.y};if(dist(n,guest)<45){guest.served=1;s.coins+=3;n.state='serving'}}else p={x:245,y:265}}
    target(n,p)}move(n,dt);n.state=n.path.length?'walking':n.served?'drinking':'seated';
  }
  for(let t of activeTalks(s)){let p=perceive(s,t),h=s.heard[t.id]||(s.heard[t.id]={dwell:0,learned:false});if(p.tier===3){h.dwell+=dt;if(h.dwell>=3&&!h.learned){h.learned=true;if(t.rumor)learn(s,t.rumor,npc(s,t.a).name,'overheard')}}else h.dwell=Math.max(0,h.dwell-dt*.5);
   let nell=npc(s,'nell');if(s.staff.hired&&t.rumor&&nell.present&&dist(nell,npc(s,t.a))<160&&line(nell,npc(s,t.a))&&!s.staff.reports.some(r=>r.id===t.rumor))s.staff.reports.push({id:t.rumor,source:npc(s,t.a).name})
  }
  if(s.day===3&&s.time>15&&!s.events.letter){s.events.letter=true;s.evidence.push({id:'letter',x:280,y:153,text:'Westbridge asks after three missing wagons. The last driver mentioned a tollhouse detour.'})}
  if(s.day===2&&s.time>110&&!s.events.spill){s.events.spill=true;s.evidence.push({id:'spill',x:620,y:240,text:'A purple puddle. Tiny paw prints. The familiar has declined responsibility.'})}
  if(s.day===6&&s.time>70&&!s.events.search){s.events.search=true;s.world.guard=s.world.leak?'The watch is asking about a stripped tollhouse':'The watch needs testimony about the road'}
  if(input.interact){let st=nearStation(s);if(st&&['ale','wine','tea','stew'].includes(st.id)){s.pour+=dt;if(s.pour>.65){act(s,'take',st.id);s.pour=0}}}else s.pour=0;
  if(s.time>=180)nextDay(s);
 }
 function nearStation(s){return DATA.stations.filter(n=>dist(s.player,n)<65&&line(s.player,n)).sort((a,b)=>dist(s.player,a)-dist(s.player,b))[0]}
 function nearNpc(s){return s.npcs.filter(n=>n.present&&!n.away&&dist(s.player,n)<65&&line(s.player,n)).sort((a,b)=>dist(s.player,a)-dist(s.player,b))[0]}
 function act(s,verb,id,opts={}){if(s.paused||s.ended)return false;let n=npc(s,id),st=nearStation(s);if(['share','sell','withhold','exploit','serve','talk','hire','report','debrief','testify','cooperate'].includes(verb)&&(!n||!n.present||n.away||(dist(s.player,n)>70||!line(s.player,n))))return false;
  if(verb==='take'){if(st?.id!==id)return false;if(s.player.carry){say(s,'Your hands are full. Serve your guest or set the dish down with X.');return false}s.player.carry=id;say(s,'Carrying '+id+'. Walk to a guest; E to offer it.');return true}
  if(verb==='discard'){s.player.carry=null;return true}
  if(verb==='serve'){if(!s.player.carry)return false;let favorite=n.favorite===s.player.carry,paid=!n.served;n.familiar+=favorite?2:1;n.served=1;s.coins+=paid?(favorite?5:3):0;n.memory.push('You brought '+s.player.carry+' on day '+s.day+'.');say(s,n.name+': '+(paid?(favorite?'You remembered. That is exactly what I needed.':'Thank you, keeper.'):'Another? Generous of you. Put it on your tab this time.'));s.player.carry=null;return true}
  if(verb==='talk'){n.familiar++;if(id==='oren')learn(s,'wagons','Oren','direct conversation');if(id==='bram'&&n.familiar>=2)learn(s,'warning','Bram','direct conversation');if(id==='tomas'&&n.familiar>=2)learn(s,'diversion','Tomas','direct conversation');return true}
  if(verb==='share'){if(!s.knowledge.wagons||s.world.leak||id!=='mira')return false;s.world.leak=true;n.known.push('wagons');s.knowledge.wagons.knownBy.push('Mira');n.memory.push('You trusted me with the wagon trail.');s.relationships['cedric:mira']='Mira is keeping something from Cedric';note(s,'You told Mira about the wagons. She promised to ask around.');say(s,'Mira: I know people who can help. Leave it with me.');return true}
  if(verb==='sell'){if(!s.knowledge.wagons||s.world.sold||id!=='oren')return false;s.world.sold=true;s.coins+=15;n.known.push('keeper knows wagons');s.knowledge.wagons.knownBy.push('Oren');n.memory.push('You sold me the road news for 15 coins.');s.world.trade='Oren controls the road story';note(s,'Oren bought your road news. He asked you to stop troubling the watch.');return true}
  if(verb==='withhold'){if(id==='tomas'&&s.events.search)s.world.guard='You declined the watch search; Tomas left without your testimony';n.memory.push('You declined to share your confidence.');note(s,'You kept your confidence from '+n.name+'.');say(s,n.name+': Fair enough. I will remember that.');return true}
  if(verb==='exploit'){if(!s.knowledge.ledger||s.world.exploited||id!=='oren')return false;s.world.exploited=true;s.coins+=25;n.memory.push('You used my ledger against me.');s.world.trade='Oren pays for your silence; the detour remains';note(s,'Oren paid 25 coins for silence. His smile did not reach his eyes.');return true}
  if(verb==='hire'){if(id!=='nell'||s.staff.hired||s.coins<12)return false;s.coins-=12;s.staff.hired=true;n.memory.push('You gave me steady work.');note(s,'Nell joined: 12 coins now, 3 additional coins each closing. Public-table service and imperfect reports.');return true}
  if(verb==='report'){if(id!=='nell')return false;for(let r of s.staff.reports)learn(s,r.id,'Nell, recalling '+r.source,'secondhand');say(s,s.staff.reports.length?'Nell: That is what I think I heard. Do not stake the roof on it.':'Nell: Nothing I could make out. I cannot hear through a wall.');return true}
  if(verb==='inspect'){if(id==='hearth'&&st?.id==='hearth'){learn(s,'carving','Treaty mark beneath the hearth','inspection');say(s,'The same three notches, carved beneath layers of soot.');return true}if(id==='room'&&st?.id==='room'&&!s.events['room'+s.day]){s.events['room'+s.day]=true;s.coins+=4;say(s,'You straighten room two. Four coins lie beside a note: the familiar did not eat the curtain.');return true}let e=s.evidence.find(e=>e.id===id&&dist(e,s.player)<75);if(e){if(id==='letter'){learn(s,'wagons','Westbridge letter','letter');learn(s,'diversion','Westbridge driver, by letter','letter')}say(s,e.text);if(id==='spill'){s.evidence=s.evidence.filter(v=>v!==e);s.coins+=1}return true}return false}
  if(verb==='dispatch'){if(st?.id!=='board'||s.quest||!s.knowledge.wagons||s.day>4)return false;let party=['cedric',...(opts.bram?['bram']:[])],cost=8+(opts.bram?6:0)+(opts.supplies?4:0);if(s.coins<cost||party.some(id=>!npc(s,id).present||npc(s,id).away))return false;s.coins-=cost;s.quest={party,bram:!!opts.bram,supplies:!!opts.supplies,cautious:!!opts.cautious,warning:!!opts.warning&&!!s.knowledge.warning,departDay:s.day,returnDay:s.day+2,resolved:false,debriefed:false};for(let id of party){let n=npc(s,id);n.away=true;n.goal=null}note(s,'The party leaves for the Blackwood tollhouse. They expect two days on the road.');return true}
  if(verb==='debrief'){if(id!=='cedric'||!s.quest?.resolved||s.quest.debriefed)return false;s.quest.debriefed=true;let o=s.quest.outcome;if(o==='proof'){learn(s,'ledger','Stamped tollhouse ledger','physical evidence',true);s.coins+=12;say(s,'Cedric: We came home. With proof. Bram even let me carry the ledger.');s.world.trade='Proof of the detour has reached the inn'}else if(o==='compromised'){s.knowledge.wagons.knownBy.push('Reed Knives');learn(s,'diversion','Cedric at the stripped tollhouse','eyewitness');s.relationships['cedric:mira']='Cedric distrusts Mira after the warehouse raid';say(s,'Cedric: The Reed Knives got there first. Mira knew where we were going. How?');note(s,'The tollhouse was stripped before your party arrived. Cedric is asking who told Mira.')}else{learn(s,'diversion','Injured Cedric','eyewitness');say(s,'Cedric: The bridge gave way. We had to turn back. I thought you knew the road.');note(s,'Cedric returned injured. Preparation would have changed this journey.')}return true}
  if(verb==='cooperate'){if(id!=='tomas'||!s.events.search)return false;s.world.guard=s.knowledge.ledger?'Tomas has your evidence and permission to search':'Tomas searched but found no proof';n.memory.push('You cooperated with the watch search.');note(s,s.world.guard+'.');say(s,'Tomas: Thank you. I will write down what we actually found.');return true}
  if(verb==='testify'){if(id!=='tomas'||!s.knowledge.ledger)return false;s.world.guard='Tomas holds the ledger testimony';s.world.trade='The watch reopened the road; trade returns to Rookcross';n.memory.push('You gave evidence, not just a name.');s.knowledge.ledger.knownBy.push('Tomas');note(s,'You gave Tomas the ledger. The watch can act on evidence.');return true}
  if(verb==='sleep'){if(st?.id!=='bed'||s.time<145)return false;return nextDay(s)}return false;
 }
 function summary(s){return ['You kept the inn for seven days.',s.staff.hired?'Nell has a steady wage and a little more boat money.':'You carried the plates yourself.',s.quest?(s.quest.outcome==='proof'?'Cedric returned with proof and a story he can tell his sister.':s.quest.outcome==='compromised'?'Your party came home to a secret already spent. Cedric and Mira have things to say.':s.quest.outcome==='injured'?'Cedric came home hurt. Next time, preparation matters.':'An expedition is still on the road.'):'No expedition left your door this week.',s.world.leak?'Mira passed your confidence to the Reed Knives. Information kept moving after you let it go.':'Mira never received the wagon trail from you.',s.world.trade+'.',s.debt?'Oren is owed '+s.debt+' coins in favors.':'The roof is still yours.',s.knowledge.carving?'And those names beneath the hearth still do not explain themselves.':'The old inn has more to tell.']}
 return {fresh,tick,act,dist,line,route,blocked,learn,npc,activeTalks,perceive,nearNpc,nearStation,nextDay,summary};
})();
if(typeof module!=='undefined')module.exports=Sim;
